### PR TITLE
PHP 7 Support

### PR DESCRIPTION
**Pull request by Sean-Der**
This is a start for PHP 7 support, this only compiles WITHOUT APC/APCU currently (that should be fixed today)

Going through and fixing test fails now

### CODE REVIEW

**Comment by Sean-Der** [comment]
@Jan-E you are fast to catch things! a42f95067b11885fcbc4b438e98f23e4d9878498 should fix the build, thanks again for being on top of this.

Below are the current test fails, really hoping to finish this today!
```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   60
---------------------------------------------------------------------
Number of tests :   46                44
Tests skipped   :    2 (  4.3%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    5 ( 10.9%) ( 11.4%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   39 ( 84.8%) ( 88.6%)
---------------------------------------------------------------------
Time taken      :    2 seconds
=====================================================================
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Check for reference serialisation [tests/igbinary_009.phpt]
Cyclic array test [tests/igbinary_026.phpt]
Cyclic array test 2 [tests/igbinary_026b.phpt]
Object test, cyclic references [tests/igbinary_033.phpt]
Check for double extremes [tests/igbinary_044.phpt]
=====================================================================
```

**Comment by Jan-E** [comment]
@Sean-Der I am getting the same testresults on Windows, even after https://github.com/Sean-Der/igbinary/commit/f7920f0f58f970938d6aea9825fe9809f400f103
_033.phpt is still failing...

And I am on top of it, because I have got a spare laptop that compiles PHP7 every once in a while. It is my backup laptop that is put to good use.

**Comment by Sean-Der** [comment]
Hey @phadej I am stuck on the reference/recursive deserialization code :/
I have been trying to debug/learn it, but can't seem to figure out the issue! I keep taking `$a = array(&$a)` to `$a = array(array(&$a))`

Anyway, I have a busy work week so I don't think I will be able to touch this until the end of the week. If anyone wants to dive in and review/cleanup/fix the last test fails that would be awesome. Thanks!

**Comment by phadej** [comment]
As I commented in https://github.com/igbinary/igbinary/issues/40, you might be doing unnecessary work with this PR.

@tricky is working on his version and I my understanding struggles with something similar (i.e. problems with circular references). And I have no experience in PHP7 internals, so cannot comment further.

**Comment by Jan-E** [comment]
@tricky is not sharing his progress, so we have no idea what is going on. I hope he is doing his work with annotated commits. One big commit with all his work will be very hard to troubleshoot. @Sean-Der does everything with separate commits. In case of issues a git bisect will be a lot easier.

**Comment by tricky** [comment]
Sorry to dissapoint you @Jan-E yes, unfortunately my work is in two commits. Still, we're not going to use either of my big commits directly. They will of course be split into reasonable pieces as well as include more tests.

**Comment by razvanphp** [comment]
@Sean-Der I added this test in #54 that is failing in your branch, the behavior is triggered by Yii 1 Framework code.

Can you please have a look? For me the playground branches are way worse than this with PHP 7.0.0RC6, I would love to see compatible igbinary since the GA release is in only 10 days!

**Comment by phadej** [comment]
This PR seems to be obsolete. If you're still want to continue, please make PR against https://github.com/igbinary/igbinary7

**Pull request closed without merging**
