### PR TITLE
Php7 dev

### PR DESCRIPTION
**Pull request by Jan-E**
The first commit is to see what the changes are.
The second commit is just improving the readability.

### CODE REVIEW

**Comment by phadej** [comment]
I don't understand, is this something `master` would benefit from?

**Comment by Jan-E** [comment]
It would not hurt in master, but it will not do anything there as long as master is not compiled for PHP7 with VC14. The original code of ig_win32.h compiles fine with VC9 (PHP 5.3/5.4) and VC11 (PHP 5.5/5.6), but generates a fatal error in VC14 (PHP7). VC14 has a stdbool.h that does the same as the original VC9/VC11 code. So the VC14 fix is to include stdbool.h.

The line

    #if _MSC_VER >= 1900

checks if VC >= VC14, so for VC14 and all future versions ig_win32.h will

    #include <stdbool.h>

**Comment by phadej** [comment]
So no-one uses VC14 to compile PHP5.5? I have to dig into windows.

**Comment by Jan-E** [comment]
No. PHP 5.3 & PHP 5.4 are compiled by VC9
PHP 5.5 & PHP 5.6 by VC11
And PHP 7 by VC14

http://windows.php.net/download/ - VC11 x86 Non Thread Safe (2015-Aug-05 23:24:00) etc
http://windows.php.net/qa/ - VC14 x86 Non Thread Safe (2015-Aug-21 02:01:38) etc

**Comment by phadej** [comment]
https://github.com/igbinary/igbinary7

**Pull request closed without merging**
